language: python
python: 
  - "3.6"

services:
  - mysql

env:
  - DJANGO=3.1.6 DB=mysql DJANGO_ENVIRONMENT=travis

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database ensembl_metadata;' -u root

script:
  - python manage.py test  --settings=ensembl_metadata.settings.test
