language: python

python: 
   - "3.5"

services: 
  - mysql

env: 
  - DJANGO=1.11 DB=mysql DJANGO_ENVIRONMENT=staging

install: 
  - pip install -r requirements.txt

before_script: 
  - mysql -e 'create database ensembl_metadata_registry;' -u root
  - mysql -e 'create database ensembl_metadata;' -u root

script: 
  - python3 ensembl_metadata_registry/manage.py test assembly.tests compara.tests datarelease.tests division.tests genomeinfo.tests meta_stats.tests ncbi_taxonomy.tests  --settings=ensembl_metadata_registry.settings.test

