language: python
os: linux

python:
  - "3.8"

services:
  - mysql

env:
  - DJANGO=3.1.7

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - python manage.py test  --settings=metadata_registry.settings.test
