language: python
python: 
  - "3.6"

services:
  - mysql

env:
  - DJANGO=3.1.6

install:
  - pip install -r requirements.txt

script:
  - python manage.py test  --settings=metadata_registry.settings.test
