language: python
python: 
  - "3.5"

services:
  - mysql

env:
  -DJANGO=1.10 DB=mysql

install:
  - pip3 install -r requirements.txt

before_script:
  - mysql -e 'create database ensembl_metadata;' -u root
  - mysql -e 'create database ensembl_metadata_registry;' -u root

script:
  - python3 manage.py test
