# Generated by Django 3.1.7 on 2021-07-20 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0006_auto_20210415_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblysequence',
            name='checksum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='assemblysequence',
            name='ga4gh_identifier',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
