# Generated by Django 3.1.7 on 2021-09-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0009_auto_20210811_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assemblysequence',
            old_name='checksum',
            new_name='sequence_checksum',
        ),
    ]
