# Generated by Django 3.1.7 on 2022-03-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0012_auto_20210922_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='genome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to='ensembl_metadata.genome'),
        ),
        migrations.AddField(
            model_name='organism',
            name='scientific_parlance_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
