# Generated by Django 3.1.7 on 2022-03-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0012_auto_20210922_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='scientific_parlance_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
