# Generated by Django 3.2.18 on 2023-05-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datasets_set', to='ensembl_metadata.attribute'),
        ),
        migrations.AlterField(
            model_name='datasetattribute',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attributes', to='ensembl_metadata.dataset'),
        ),
    ]
