# Generated by Django 3.2.18 on 2023-05-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0002_auto_20230524_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assembly',
            old_name='tolid',
            new_name='tol_id',
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('percent', 'Percent'), ('string', 'String'), ('bp', 'BP')], default='string', max_length=8),
        ),
        migrations.AddField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('progressing', 'Progressing'), ('processed', 'Processed')], default='string', max_length=12),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='datasetattribute',
            unique_together={('dataset', 'attribute', 'value')},
        ),
        migrations.RemoveField(
            model_name='datasetattribute',
            name='type',
        ),
    ]
