# Generated by Django 3.2.17 on 2023-06-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0002_auto_20230524_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assembly',
            old_name='tolid',
            new_name='tol_id',
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('percent', 'Percent'), ('string', 'String'), ('bp', 'BP')], default='string', max_length=8),
        ),
        migrations.AddField(
            model_name='dataset',
            name='genomes',
            field=models.ManyToManyField(through='ensembl_metadata.GenomeDataset', to='ensembl_metadata.Genome'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('progressing', 'Progressing'), ('processed', 'Processed')], default='string', max_length=12),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='genomedataset',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='genome_datasets', to='ensembl_metadata.dataset'),
        ),
        migrations.AlterField(
            model_name='genomedataset',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ensembl_metadata.ensemblrelease'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetattribute',
            unique_together={('dataset', 'attribute', 'value')},
        ),
        migrations.RemoveField(
            model_name='datasetattribute',
            name='type',
        ),
    ]
