# Generated by Django 3.2.17 on 2023-06-19 14:11

from django.db import migrations, models
import uuid
from ensembl.production.metadata.admin.models import UUIDField


class Migration(migrations.Migration):
    dependencies = [
        ('ensembl_metadata', '0003_auto_20230607_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_uuid',
            field=UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='ensemblrelease',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genome',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='genome_uuid',
            field=UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='genomedataset',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='genomerelease',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
