# Generated by Django 3.2.19 on 2023-06-21 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0004_is_current_false'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='alt_accession',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='assembly_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='organism',
            name='organism_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensembl_metadata.datasetsource'),
        ),
        migrations.AlterField(
            model_name='datasetattribute',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ensembl_metadata.dataset'),
        ),
        migrations.AlterField(
            model_name='genomedataset',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genome_datasets', to='ensembl_metadata.dataset'),
        ),
        migrations.AlterField(
            model_name='genomedataset',
            name='genome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensembl_metadata.genome'),
        ),
    ]
