# Generated by Django 3.2.19 on 2023-06-27 13:27

from django.db import migrations, models
import uuid
from ensembl.production.metadata.admin.models import UUIDField


class Migration(migrations.Migration):
    dependencies = [
        ('ensembl_metadata', '0005_assem_org_uuid_alt_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='genome_uuid',
            field=UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
