# Generated by Django 3.2.19 on 2023-08-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0007_auto_20230630_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assemblysequence',
            old_name='ga4gh_identifier',
            new_name='md5',
        ),
        migrations.RenameField(
            model_name='organism',
            old_name='display_name',
            new_name='common_name',
        ),
        migrations.RemoveField(
            model_name='assemblysequence',
            name='sequence_checksum',
        ),
        migrations.RemoveField(
            model_name='organism',
            name='url_name',
        ),
        migrations.AddField(
            model_name='assembly',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assembly',
            name='url_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='assemblysequence',
            name='chromosome_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assemblysequence',
            name='sha512t4u',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='genomerelease',
            name='is_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assemblysequence',
            name='chromosomal',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='organismgroupmember',
            name='is_reference',
            field=models.BooleanField(null=True),
        ),
    ]
