# Generated by Django 3.1.7 on 2021-08-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0007_auto_20210720_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='DatasetAttribute',
            fields=[
                ('dataset_attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=128)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ensembl_metadata.attribute')),
            ],
            options={
                'db_table': 'dataset_attribute',
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='label',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='datasettype',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasettype',
            name='label',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='DatasetStatistic',
        ),
        migrations.AddField(
            model_name='datasetattribute',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ensembl_metadata.dataset'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetattribute',
            unique_together={('dataset', 'attribute', 'type')},
        ),
    ]
