# Generated by Django 3.2.19 on 2023-08-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0009_strain_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='assembly_default',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
