# Generated by Django 3.1.7 on 2021-09-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0010_auto_20210901_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblysequence',
            name='accession',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='assemblysequence',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='assemblysequence',
            unique_together={('assembly', 'accession')},
        ),
    ]
