# Generated by Django 3.2.19 on 2023-12-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0012_CASCADE_prod_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={'ordering': ['biosample_id', 'scientific_name']},
        ),
        migrations.RenameField(
            model_name='organism',
            old_name='ensembl_name',
            new_name='biosample_id',
        ),
    ]
