# Generated by Django 3.2.19 on 2023-12-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0013_organism_biosample_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblysequence',
            name='is_circular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assemblysequence',
            name='type',
            field=models.CharField(blank=True, default='primary_assembly', max_length=26),
        ),
    ]
