# Generated by Django 3.2.19 on 2023-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0014_sequence_type_is_circular'),
    ]

    operations = [

        migrations.AlterField(
            model_name='organismgroup',
            name='type',
            field=models.CharField(choices=[('Division', 'Ensembl GB Division'), ('Internal', 'Internal Grouping'), ('Population', 'Organisms population'), ('Species', 'Organisms species'), ('Compara', 'Organisms Comparative Genomics group')], max_length=32, null=True),
        ),
    ]
