# Generated by Django 3.2.25 on 2024-07-12 11:07

from django.db import migrations, models
import ensembl.production.metadata.admin.models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_metadata', '0020_auto_20240425_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ensemblrelease',
            options={},
        ),
        migrations.AlterField(
            model_name='assembly',
            name='assembly_uuid',
            field=ensembl.production.metadata.admin.models.UUIDField(default='4bde0b3b-9aa7-491f-8744-61e8c990e3ef', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_uuid',
            field=ensembl.production.metadata.admin.models.UUIDField(default='ae8f4985-6d2f-48f2-8969-fe89e8711464', editable=False),
        ),
        migrations.AlterField(
            model_name='datasetattribute',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='genome',
            name='genome_uuid',
            field=ensembl.production.metadata.admin.models.UUIDField(default='300368f7-9242-4486-86ff-c43908e893c7', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organism',
            name='organism_uuid',
            field=ensembl.production.metadata.admin.models.UUIDField(default='cfe44753-1835-48ab-a1bb-21d682bfbd10', editable=False, unique=True),
        ),
    ]
